LAYER_LOCK_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

OLED_ENABLE				= yes
OLED_DRIVER 			= ssd1306
OLED_TRANSPORT 			= i2c

WPM_ENABLE              = no   # WPM Calculation

CONSOLE_ENABLE			= no
COMBO_ENABLE 			= no
BACKLIGHT_ENABLE		= no
AUDIO_ENABLE			= no
RGB_MATRIX_ENABLE		= no
LEADER_ENABLE			= no